plugin: ENC[AES256_GCM,data:Z4bJuNVZvduM70paZ22AoMPD5XHx,iv:Frteek9kZekW+ecvljSH9v2laWpWP5nwZzFnmiQwR30=,tag:cqPANB4FfPxOFU1rUz9hOg==,type:str]
token: ENC[AES256_GCM,data:w7bc+/xTD5OfcBNYoOGhzV5BJoq8jIH8bZwbNez8ZOl8v4jCxcNZuQ0gRSm4HZNGWcLVBk863Rh/mg8zsxGzEQ==,iv:h7K3hr2C78oJ4Jhy0Ibxln9TK4EcvAMs9jtYHmFbc4U=,tag:sSC172eez7Q65npWjDjM7g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault:
    -   vault_address: https://vault.pandentia.qcx.io
        engine_path: transit/cluster
        key_name: automata
        created_at: '2021-03-29T18:22:26Z'
        enc: vault:v1:MODqE3SqoRw87ATFctxbRoZXeldRmhII2Mj2Fu6wO8qrDPOcEPe7VoEUMXeYgyl8Lw5fPWVgu4EN4NdM
    lastmodified: '2021-03-29T19:00:57Z'
    mac: ENC[AES256_GCM,data:b/pKNoDV78YR+WJYaG1RxzFKFU0FmHc4CHt/8g61uFac5Rp/fBNNWxKbnLUiUxG91nz/YWL4U9T5k4vi+JYl4Axuy1rAz2wkF4N5umUaF1EtfRl4cUGWeWuKda3p54Enuh+4wjLmlf5r5z0mrV7pRwoiudD5PHToDfVeKcLOa2I=,iv:Dq6WczkA++zRJcEr3CH26EqmUf0nqGC6eas9u/fb/Vg=,tag:3iHrK6u7GZKf3sQ+Pif+oA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
