- Sid: IAMAllowListBucket${sha1(bucket)}
  Effect: Allow
  Resource: arn:aws:s3:::${bucket}
  Action:
    - s3:ListBucket
    - s3:ListBucketVersions
    - s3:GetBucket*
    - s3:GetEncryptionConfiguration
    - s3:GetLifecycleConfiguration

- Sid: IAMAllowInteractBucket${sha1(bucket)}
  Effect: Allow
  Resource: arn:aws:s3:::${bucket}/*
  Action:
    - s3:GetObject
    - s3:PutObject
    - s3:DeleteObject
    - s3:RestoreObject
    - s3:ListBucketVersions
    - s3:GetObjectVersion
    - s3:DeleteObjectVersion
