#cloud-config
users:
  - name: pandentia
    gecos: Cassandra Beelen
    # doesn't work on Fedora, thanks cloud-init!
    # ssh_import_id: gh:SapphicCode
    ssh_authorized_keys: ${keys}
    sudo: ALL=(ALL) NOPASSWD:ALL

ssh_pwauth: no
